In [60]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.10/dist-packages (8.1.0)
Requirement already satisfied: protobuf<=4.21.12,>=4.21.1 in /usr/local/lib/python3.10/dist-packages (from mysql-connector-python) (4.21.12)

In [61]:
import mysql.connector

mydb = mysql.connector.connect(
  host="162.241.60.182",
  user="leudadoc_henry",
  password="tenboj-dEckow-nokka8",
  database="leudadoc_Henry"
)

mycursor = mydb.cursor()

In [66]:
mycursor.execute("SHOW TABLES")

for table in mycursor:
  print(table)

('Rest_google',)
('categorias',)
('clientes',)
('estados',)

In [63]:
#Tabla Estados
mycursor.execute("CREATE TABLE IF NOT EXISTS estados (stateID int AUTO_INCREMENT, state varchar(255), primary key (stateID))")

In [64]:
#Tabla Clientes
mycursor.execute("CREATE TABLE IF NOT EXISTS clientes (clientID int, name varchar(255), primary key (clientID))")

In [65]:
#Tabla Categoria
mycursor.execute("CREATE TABLE IF NOT EXISTS categorias (categoryID int AUTO_INCREMENT, category varchar(255), primary key (categoryID))")

In [ ]:
#Tabla Local
mycursor.execute("CREATE TABLE IF NOT EXISTS locales (storeID int, name varchar(255), )")
create table restaurant (
gmapID int,
name varchar(255),
address varchar(255),
latitude decimal(9,6),
longitude decimal(9,6),
state varchar(255),
delivery varchar(255),
permanently_closed varchar(255)
);

In [ ]:
#Tabla intermedia Categoria_Local
mycursor.execute("CREATE TABLE IF NOT EXISTS categoria_local (categoryID int not null, storeID int not null)")

In [ ]:
#Tabla review
mycursor.execute("CREATE TABLE IF NOT EXISTS reviews (reviewID int AUTO_INCREMENT, clientID int not null, storeID int not null, date datetime, rating int, text varchar(255),primary key (reviewID), FOREIGN KEY (clientID) REFERENCES clientes(clientID), FOREIGN KEY (storeID) REFERENCES stores(storeID))")

DatabaseError: ignored

stateID INT, FOREIGN KEY (stateID) REFERENCES estado(stateID))")

In [ ]:
mycursor.execute("CREATE TABLE IF NOT EXISTS review (reviewID int not null , clienteID int not null, gmapID int not null, date datetime, rating int, text varchar(255), primary key (reviewID) )")

SyntaxError: ignored